import PricingC.RemainingOrbit00
import PricingC.RemainingOrbit01
import PricingC.RemainingOrbit02
import PricingC.RemainingOrbit03
import PricingC.RemainingOrbit04
import PricingC.RemainingOrbit05
import PricingC.RemainingOrbit06
import PricingC.RemainingOrbit07
import PricingC.RemainingOrbit08
import PricingC.RemainingOrbit09
import PricingC.RemainingOrbit10
import PricingC.RemainingOrbit11
import PricingC.RemainingOrbit12
import PricingC.RemainingOrbit13
import PricingC.RemainingOrbit14
import PricingC.RemainingOrbit15
import PricingC.RemainingOrbit16
import PricingC.RemainingOrbit17
import PricingC.RemainingOrbit18
import PricingC.RemainingOrbit19
import PricingC.RemainingOrbit20
import PricingC.RemainingOrbit21
import PricingC.RemainingOrbit22
import PricingC.RemainingOrbit23
import PricingC.RemainingOrbit24
import PricingC.RemainingOrbit25
import PricingC.RemainingOrbit26
import PricingC.RemainingOrbit27
import PricingC.RemainingOrbit28
import PricingC.RemainingOrbit29
import PricingC.RemainingOrbit30
import PricingC.RemainingOrbit31
import PricingC.RemainingOrbit32
import PricingC.RemainingOrbit33
import PricingC.RemainingOrbit34
import PricingC.RemainingOrbit35
import PricingC.RemainingOrbit36
import PricingC.RemainingOrbit37
import PricingC.RemainingOrbit38
import PricingC.RemainingOrbit39
import PricingC.RemainingOrbit40
import PricingC.RemainingOrbit41
import PricingC.RemainingOrbit42
import PricingC.RemainingOrbit43
import PricingC.RemainingOrbit44
import PricingC.RemainingOrbit45
import PricingC.RemainingOrbit46
import PricingC.RemainingOrbit47
import PricingC.RemainingOrbit48
import PricingC.RemainingOrbit49
import PricingC.RemainingOrbit50
import PricingC.RemainingOrbit51
import PricingC.RemainingOrbit52
import PricingC.RemainingOrbit53
import PricingC.RemainingOrbit54
import PricingC.RemainingOrbit55
import PricingC.SelectedOrbitBinding0
import PricingC.SelectedOrbitBinding1
import PricingC.SelectedOrbitBinding2
import PricingC.SelectedOrbitBinding3
import PricingC.SelectedOrbitBinding4
import PricingC.SelectedOrbitBinding5
import PricingC.SelectedOrbitBinding6
import PricingC.SelectedOrbitBinding7
import PricingC.ThreeSupportUnbalanced
import PricingC.NativeActionPhysical
#print axioms PricingC.RemainingOrbit00.complete_matrix_cover
#print axioms PricingC.RemainingOrbit01.complete_matrix_cover
#print axioms PricingC.RemainingOrbit02.complete_matrix_cover
#print axioms PricingC.RemainingOrbit03.complete_matrix_cover
#print axioms PricingC.RemainingOrbit04.complete_matrix_cover
#print axioms PricingC.RemainingOrbit05.complete_matrix_cover
#print axioms PricingC.RemainingOrbit06.complete_matrix_cover
#print axioms PricingC.RemainingOrbit07.complete_matrix_cover
#print axioms PricingC.RemainingOrbit08.complete_matrix_cover
#print axioms PricingC.RemainingOrbit09.complete_matrix_cover
#print axioms PricingC.RemainingOrbit10.complete_matrix_cover
#print axioms PricingC.RemainingOrbit11.complete_matrix_cover
#print axioms PricingC.RemainingOrbit12.complete_matrix_cover
#print axioms PricingC.RemainingOrbit13.complete_matrix_cover
#print axioms PricingC.RemainingOrbit14.complete_matrix_cover
#print axioms PricingC.RemainingOrbit15.complete_matrix_cover
#print axioms PricingC.RemainingOrbit16.complete_matrix_cover
#print axioms PricingC.RemainingOrbit17.complete_matrix_cover
#print axioms PricingC.RemainingOrbit18.complete_matrix_cover
#print axioms PricingC.RemainingOrbit19.complete_matrix_cover
#print axioms PricingC.RemainingOrbit20.complete_matrix_cover
#print axioms PricingC.RemainingOrbit21.complete_matrix_cover
#print axioms PricingC.RemainingOrbit22.complete_matrix_cover
#print axioms PricingC.RemainingOrbit23.complete_matrix_cover
#print axioms PricingC.RemainingOrbit24.complete_matrix_cover
#print axioms PricingC.RemainingOrbit25.complete_matrix_cover
#print axioms PricingC.RemainingOrbit26.complete_matrix_cover
#print axioms PricingC.RemainingOrbit27.complete_matrix_cover
#print axioms PricingC.RemainingOrbit28.complete_matrix_cover
#print axioms PricingC.RemainingOrbit29.complete_matrix_cover
#print axioms PricingC.RemainingOrbit30.complete_matrix_cover
#print axioms PricingC.RemainingOrbit31.complete_matrix_cover
#print axioms PricingC.RemainingOrbit32.complete_matrix_cover
#print axioms PricingC.RemainingOrbit33.complete_matrix_cover
#print axioms PricingC.RemainingOrbit34.complete_matrix_cover
#print axioms PricingC.RemainingOrbit35.complete_matrix_cover
#print axioms PricingC.RemainingOrbit36.complete_matrix_cover
#print axioms PricingC.RemainingOrbit37.complete_matrix_cover
#print axioms PricingC.RemainingOrbit38.complete_matrix_cover
#print axioms PricingC.RemainingOrbit39.complete_matrix_cover
#print axioms PricingC.RemainingOrbit40.complete_matrix_cover
#print axioms PricingC.RemainingOrbit41.complete_matrix_cover
#print axioms PricingC.RemainingOrbit42.complete_matrix_cover
#print axioms PricingC.RemainingOrbit43.complete_matrix_cover
#print axioms PricingC.RemainingOrbit44.complete_matrix_cover
#print axioms PricingC.RemainingOrbit45.complete_matrix_cover
#print axioms PricingC.RemainingOrbit46.complete_matrix_cover
#print axioms PricingC.RemainingOrbit47.complete_matrix_cover
#print axioms PricingC.RemainingOrbit48.complete_matrix_cover
#print axioms PricingC.RemainingOrbit49.complete_matrix_cover
#print axioms PricingC.RemainingOrbit50.complete_matrix_cover
#print axioms PricingC.RemainingOrbit51.complete_matrix_cover
#print axioms PricingC.RemainingOrbit52.complete_matrix_cover
#print axioms PricingC.RemainingOrbit53.complete_matrix_cover
#print axioms PricingC.RemainingOrbit54.complete_matrix_cover
#print axioms PricingC.RemainingOrbit55.complete_matrix_cover
#check PricingC.ThreeSupportFrame.actual_455_to_catalogue
#print axioms PricingC.ThreeSupportFrame.actual_455_to_catalogue
#check PricingC.ThreeSupportFrame.actual_545_to_catalogue
#print axioms PricingC.ThreeSupportFrame.actual_545_to_catalogue
#check PricingC.ThreeSupportFrame.actual_554_to_catalogue
#print axioms PricingC.ThreeSupportFrame.actual_554_to_catalogue
#check PricingC.ThreeSupportFrame.actual_555_to_catalogue
#print axioms PricingC.ThreeSupportFrame.actual_555_to_catalogue
#check PricingC.NativeActionPhysical.physical_edge_transport
#print axioms PricingC.NativeActionPhysical.physical_edge_transport
