import R4333Lean.CatalogueBaseCNFSemantics

/-! Generated finite data for the certified Clebsch-complement exhaustion. -/

namespace R4333

def canonicalClebschRedCodes : Finset Nat :=
  {4, 7, 10, 12, 13, 21, 23, 25, 28, 30, 38, 39, 40, 45, 46, 59, 60, 61, 62, 63, 72, 73, 75, 78, 88, 90, 91, 93, 105, 106, 107, 108, 123, 127, 140, 143, 157, 159, 174, 175}

def clebschComplementEdges : List (Nat × Nat) :=
  [(0, 1), (0, 2), (0, 3), (0, 5), (0, 6), (0, 8), (0, 9), (0, 11), (0, 14), (0, 15), (1, 2), (1, 3), (1, 4), (1, 6), (1, 8), (1, 10), (1, 11), (1, 13), (1, 15), (2, 3), (2, 4), (2, 5), (2, 9), (2, 10), (2, 11), (2, 12), (2, 15), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (4, 5), (4, 6), (4, 7), (4, 10), (4, 12), (4, 13), (4, 15), (5, 6), (5, 7), (5, 9), (5, 12), (5, 14), (5, 15), (6, 7), (6, 8), (6, 13), (6, 14), (6, 15), (7, 8), (7, 9), (7, 10), (7, 12), (7, 13), (7, 14), (8, 9), (8, 10), (8, 11), (8, 13), (8, 14), (9, 10), (9, 11), (9, 12), (9, 14), (10, 11), (10, 12), (10, 13), (11, 12), (11, 13), (11, 14), (11, 15), (12, 13), (12, 14), (12, 15), (13, 14), (13, 15), (14, 15)]

def clebschComplementEdgesFin : List (Fin 16 × Fin 16) :=
  [(0, 1), (0, 2), (0, 3), (0, 5), (0, 6), (0, 8), (0, 9), (0, 11), (0, 14), (0, 15), (1, 2), (1, 3), (1, 4), (1, 6), (1, 8), (1, 10), (1, 11), (1, 13), (1, 15), (2, 3), (2, 4), (2, 5), (2, 9), (2, 10), (2, 11), (2, 12), (2, 15), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (4, 5), (4, 6), (4, 7), (4, 10), (4, 12), (4, 13), (4, 15), (5, 6), (5, 7), (5, 9), (5, 12), (5, 14), (5, 15), (6, 7), (6, 8), (6, 13), (6, 14), (6, 15), (7, 8), (7, 9), (7, 10), (7, 12), (7, 13), (7, 14), (8, 9), (8, 10), (8, 11), (8, 13), (8, 14), (9, 10), (9, 11), (9, 12), (9, 14), (10, 11), (10, 12), (10, 13), (11, 12), (11, 13), (11, 14), (11, 15), (12, 13), (12, 14), (12, 15), (13, 14), (13, 15), (14, 15)]

def clebschDecompositions : List (List Bool) := [
  [false, false, true, false, true, false, true, true, false, true, true, false, false, true, true, true, false, false, true, false, true, true, true, false, true, false, false, true, true, false, false, true, false, true, false, false, true, false, false, true, true, true, false, false, true, true, false, true, false, true, false, false, false, true, true, false, false, true, true, false, false, true, true, false, false, true, false, true, true, false, false, true, true, false, true, false, true, false, false, true]
  , [false, false, true, false, true, false, true, true, false, true, true, false, false, true, true, true, false, false, true, false, true, true, true, false, true, false, false, true, true, false, false, true, false, true, false, false, true, false, false, true, true, true, false, false, true, true, false, true, false, true, false, false, true, true, false, true, false, false, false, false, true, false, true, true, false, false, true, false, true, true, true, true, false, false, false, false, true, true, false, true]
  , [false, false, true, false, true, false, true, true, false, true, true, false, false, true, true, true, false, false, true, false, true, true, true, false, true, false, false, true, true, false, false, true, false, true, false, true, false, false, true, true, false, false, true, false, false, true, true, true, false, false, true, false, false, true, true, false, true, false, true, false, false, true, true, false, false, true, false, true, true, false, false, true, true, false, false, true, true, false, true, false]
  , [false, false, true, false, true, false, true, true, false, true, true, false, false, true, true, true, false, false, true, true, false, true, false, false, true, true, false, true, false, false, true, true, false, false, true, false, false, true, false, true, true, true, false, true, false, true, false, true, false, true, false, false, false, false, true, true, false, true, true, false, false, true, true, true, false, true, false, true, false, false, false, true, true, false, true, false, true, false, false, true]
  , [false, false, true, false, true, false, true, true, false, true, true, false, true, true, true, false, true, false, false, false, false, true, true, true, false, false, true, true, true, false, false, true, false, true, false, false, true, false, true, false, true, true, false, false, true, true, false, true, false, true, false, false, false, true, true, false, false, true, true, false, false, true, true, false, false, true, false, true, false, true, true, false, true, false, true, false, false, false, true, true]
  , [false, false, true, false, true, false, true, true, false, true, true, true, false, false, true, false, false, true, true, false, true, true, true, false, true, false, false, false, true, false, true, false, false, true, false, true, true, true, false, false, true, true, false, false, true, true, false, false, true, true, false, false, false, true, false, false, true, true, true, true, false, false, true, false, false, true, false, true, true, false, false, true, true, false, true, false, true, false, false, true]
  , [false, false, true, true, false, true, false, true, false, true, true, false, false, true, true, true, false, false, true, false, true, true, true, false, true, false, false, true, false, true, false, false, true, true, false, false, true, false, false, true, true, true, true, false, true, false, false, false, false, true, true, false, true, false, true, false, false, true, true, false, false, true, false, false, false, true, true, true, true, false, false, true, true, false, true, false, true, false, false, true]
  , [false, false, true, true, false, true, false, true, false, true, true, false, true, true, true, false, true, false, false, false, false, true, true, true, false, false, true, true, false, true, false, false, true, true, false, false, true, false, true, false, true, true, true, false, true, false, false, false, false, true, true, false, true, false, true, false, false, true, true, false, false, true, false, false, false, true, true, true, false, true, true, false, true, false, true, false, false, false, true, true]
  , [false, false, true, true, false, true, false, true, false, true, true, false, true, true, true, false, true, false, false, false, false, true, true, true, false, false, true, true, false, true, false, false, true, true, false, false, true, false, true, false, true, true, true, false, true, false, false, false, false, true, true, false, true, true, false, false, true, false, false, true, false, false, true, false, true, false, true, false, true, true, true, true, false, false, false, true, false, false, true, true]
  , [false, false, true, true, false, true, false, true, false, true, true, false, true, true, true, false, true, false, false, false, false, true, true, true, false, false, true, true, false, true, false, false, true, true, true, false, false, false, true, true, false, false, true, false, false, true, false, true, false, false, true, true, true, false, true, true, false, false, true, false, false, true, false, false, false, true, true, true, false, true, true, false, true, false, false, false, true, true, true, false]
  , [false, false, true, true, false, true, false, true, false, true, true, false, true, true, true, false, true, false, false, true, false, false, true, false, false, true, true, false, false, true, true, false, false, true, true, false, true, true, false, false, true, true, false, true, true, false, false, false, false, true, true, false, true, false, false, true, false, true, true, false, false, true, false, true, false, false, true, true, false, true, true, false, true, false, true, false, false, false, true, true]
  , [false, false, true, true, false, true, false, true, false, true, true, true, false, true, false, false, true, true, false, false, false, true, true, true, false, false, true, true, false, false, true, false, true, false, false, true, false, true, true, false, true, true, true, false, true, false, false, false, true, false, true, false, false, false, true, false, true, true, true, true, false, true, false, false, false, true, true, true, false, false, true, false, true, false, true, false, false, false, true, true]
  , [false, true, false, false, true, true, true, false, false, true, false, true, false, true, false, true, true, false, true, false, true, true, false, true, true, false, false, true, true, false, false, true, true, false, false, false, true, false, false, true, true, true, false, false, true, true, false, true, false, true, false, false, false, true, true, false, false, true, false, true, false, true, true, false, true, true, false, false, true, false, false, true, true, false, true, false, true, false, false, true]
  , [false, true, false, false, true, true, true, false, false, true, false, true, false, true, false, true, true, false, true, false, true, true, false, true, true, false, false, true, true, false, false, true, true, false, false, true, false, false, true, true, false, false, true, false, false, true, true, true, false, false, true, false, false, true, true, false, true, false, false, true, false, true, true, false, true, true, false, false, true, false, false, true, true, false, false, true, true, false, true, false]
  , [false, true, false, false, true, true, true, false, false, true, false, true, false, true, false, true, true, false, true, false, true, true, false, true, true, false, false, true, true, false, false, true, true, false, false, true, false, false, true, true, false, false, true, false, false, true, true, true, false, false, true, false, true, false, true, true, false, false, false, false, true, true, false, true, false, true, true, false, false, true, true, false, true, false, false, false, true, true, true, false]
  , [false, true, false, false, true, true, true, false, false, true, false, true, false, true, false, true, true, false, true, true, true, false, false, false, true, true, false, false, true, false, true, true, false, false, true, true, false, true, false, true, false, false, false, true, false, true, true, true, false, false, true, false, false, true, false, true, true, false, false, true, false, true, true, true, true, false, false, false, true, false, false, true, true, false, false, true, true, false, true, false]
  , [false, true, false, false, true, true, true, false, false, true, false, true, true, false, true, false, true, false, true, false, true, true, false, true, true, false, false, false, true, true, false, false, true, true, false, true, true, false, true, false, false, false, true, false, false, true, true, false, false, true, true, false, true, true, false, false, true, false, false, true, false, false, true, false, true, true, false, false, true, true, false, true, true, false, false, true, true, false, true, false]
  , [false, true, false, false, true, true, true, false, false, true, true, true, false, true, false, false, true, true, false, false, false, true, false, true, false, true, false, true, true, false, false, true, true, false, false, true, false, true, true, false, true, false, true, false, false, true, true, true, false, false, true, false, false, true, true, false, true, false, false, true, false, true, true, false, true, true, false, true, false, false, false, false, true, true, true, true, false, false, true, false]
  , [false, true, false, true, true, true, false, true, false, false, false, true, false, true, false, true, true, false, true, false, true, false, true, true, false, false, true, true, true, false, false, true, true, false, false, true, false, false, true, true, false, false, true, false, true, false, true, true, false, false, true, false, false, true, true, false, true, false, false, true, false, true, true, false, true, false, true, false, true, false, true, true, false, false, false, true, false, false, true, true]
  , [false, true, false, true, true, true, false, true, false, false, false, true, true, false, true, false, true, false, true, false, true, false, true, true, false, false, true, false, true, true, false, false, true, true, false, true, true, false, true, false, false, false, true, false, true, false, true, false, false, true, true, false, true, false, true, false, false, true, true, false, false, true, false, false, false, true, true, true, false, true, true, false, true, false, true, false, false, false, true, true]
  , [false, true, false, true, true, true, false, true, false, false, false, true, true, false, true, false, true, false, true, false, true, false, true, true, false, false, true, false, true, true, false, false, true, true, false, true, true, false, true, false, false, false, true, false, true, false, true, false, false, true, true, false, true, true, false, false, true, false, false, true, false, false, true, false, true, false, true, false, true, true, true, true, false, false, false, true, false, false, true, true]
  , [false, true, false, true, true, true, false, true, false, false, false, true, true, false, true, false, true, false, true, false, true, false, true, true, false, false, true, false, true, true, false, false, true, true, true, false, true, false, false, true, false, false, false, false, true, true, false, true, false, true, false, true, true, true, false, true, false, false, false, true, false, false, true, false, true, false, true, false, true, true, true, true, false, false, false, false, true, true, false, true]
  , [false, true, false, true, true, true, false, true, false, false, false, true, true, false, true, false, true, false, true, true, false, false, false, true, false, true, true, false, false, true, true, false, true, false, true, true, false, true, true, false, false, false, true, true, false, false, true, false, false, true, true, false, true, false, false, true, true, false, false, true, false, false, true, true, true, false, true, false, false, true, true, true, false, false, false, true, false, false, true, true]
  , [false, true, false, true, true, true, false, true, false, false, true, true, false, false, true, false, false, true, true, false, true, false, true, false, false, true, false, false, true, true, false, false, true, true, false, true, true, true, false, false, true, false, true, false, true, false, true, false, false, true, true, false, true, true, false, false, true, false, false, true, false, false, true, false, true, false, true, true, true, false, false, true, false, true, true, true, false, false, false, true]
  , [false, true, true, false, false, true, false, false, true, true, false, true, false, true, false, true, true, false, true, false, true, true, false, true, true, false, false, true, false, false, true, false, true, false, false, true, false, false, true, true, false, true, true, true, false, false, true, false, true, false, true, false, false, false, true, false, true, true, true, true, false, true, false, false, true, true, false, false, true, false, false, true, true, false, false, true, true, false, true, false]
  , [false, true, true, false, false, true, false, false, true, true, true, false, true, true, true, false, true, false, false, false, false, true, false, true, false, true, false, true, false, true, false, false, true, true, false, false, true, false, true, false, true, true, true, true, false, false, true, false, false, true, true, false, true, false, true, false, false, true, true, false, false, true, false, false, true, true, false, true, false, true, false, false, true, true, true, true, false, false, true, false]
  , [false, true, true, false, false, true, false, false, true, true, true, true, false, true, false, false, true, true, false, false, false, true, false, true, false, true, false, true, false, false, true, false, true, false, false, true, false, true, true, false, true, true, true, true, false, false, true, false, true, false, true, false, false, false, true, false, true, true, true, true, false, true, false, false, true, true, false, true, false, false, false, false, true, true, true, true, false, false, true, false]
  , [false, true, true, false, false, true, false, false, true, true, true, true, false, true, false, false, true, true, false, false, false, true, false, true, false, true, false, true, false, false, true, false, true, false, false, true, false, true, true, false, true, true, true, true, false, false, true, false, true, false, true, false, true, false, false, true, true, false, false, true, true, false, false, true, true, false, true, false, false, true, true, false, false, true, false, true, false, true, true, false]
  , [false, true, true, false, false, true, false, false, true, true, true, true, false, true, false, false, true, true, false, false, false, true, false, true, false, true, false, true, false, false, true, false, true, false, true, false, false, true, false, true, true, true, false, true, false, true, false, true, true, false, false, true, false, false, true, true, false, true, true, true, false, true, false, false, true, true, false, true, false, false, false, false, true, true, true, false, true, true, false, false]
  , [false, true, true, false, false, true, false, false, true, true, true, true, false, true, false, false, true, true, false, false, true, false, true, false, false, true, false, false, true, false, true, false, false, true, false, true, true, true, false, false, true, true, false, true, true, false, true, false, true, false, true, false, false, true, false, false, true, true, true, true, false, true, false, false, true, false, false, true, true, false, false, false, true, true, true, true, false, false, true, false]
  , [false, true, true, false, true, false, false, true, true, false, false, true, true, false, true, false, true, false, true, false, true, false, true, true, false, false, true, false, true, false, true, false, false, true, false, true, true, false, true, false, false, true, false, true, true, false, true, false, true, true, false, false, false, true, false, false, true, true, true, true, false, false, true, false, true, false, false, false, true, true, true, true, false, false, false, true, false, false, true, true]
  , [false, true, true, false, true, false, false, true, true, false, true, false, false, true, true, true, false, false, true, false, true, false, true, false, false, true, false, true, true, false, false, true, false, true, false, false, true, false, false, true, true, true, false, true, true, false, true, true, false, true, false, false, false, true, true, false, false, true, true, false, false, true, true, false, true, false, false, true, true, false, false, true, false, true, true, true, false, false, false, true]
  , [false, true, true, false, true, false, false, true, true, false, true, true, false, false, true, false, false, true, true, false, false, true, false, true, false, true, false, true, false, false, true, false, true, false, false, true, false, true, true, false, true, true, true, true, false, false, true, false, true, true, false, false, false, false, true, false, true, true, true, true, false, false, true, false, true, true, false, true, false, false, false, true, false, true, true, true, false, false, false, true]
  , [false, true, true, false, true, false, false, true, true, false, true, true, false, false, true, false, false, true, true, false, true, false, true, false, false, true, false, false, true, false, true, false, false, true, false, true, true, true, false, false, true, true, false, true, true, false, true, false, true, true, false, false, false, true, false, false, true, true, true, true, false, false, true, false, true, false, false, true, true, false, false, true, false, true, true, true, false, false, false, true]
  , [false, true, true, false, true, false, false, true, true, false, true, true, false, false, true, false, false, true, true, false, true, false, true, false, false, true, false, false, true, false, true, false, false, true, false, true, true, true, false, false, true, true, false, true, true, false, true, false, true, true, false, false, true, false, false, true, false, true, true, false, true, false, false, true, false, false, true, true, false, true, true, false, false, true, true, false, false, true, false, true]
  , [false, true, true, false, true, false, false, true, true, false, true, true, false, false, true, false, false, true, true, false, true, false, true, false, false, true, false, false, true, false, true, false, false, true, true, true, false, true, false, true, false, false, false, true, false, true, true, true, true, false, false, true, false, true, false, true, true, false, true, true, false, false, true, false, true, false, false, true, true, false, false, true, false, true, false, true, true, true, false, false]
  , [true, false, false, true, false, true, true, false, false, true, false, false, true, true, false, true, true, false, false, true, false, true, false, true, true, false, true, true, false, true, false, true, true, false, false, false, true, false, true, false, true, true, true, false, true, false, false, false, false, true, true, false, true, false, true, false, false, true, false, false, true, true, false, true, false, true, true, false, false, true, true, false, true, false, true, false, false, false, true, true]
  , [true, false, false, true, false, true, true, false, false, true, false, false, true, true, false, true, true, false, false, true, false, true, false, true, true, false, true, true, false, true, false, true, true, false, true, false, false, false, true, true, false, false, true, false, false, true, false, true, false, false, true, true, false, true, true, false, true, false, false, true, false, true, true, false, true, true, false, false, true, false, false, true, true, false, false, true, true, false, true, false]
  , [true, false, false, true, false, true, true, false, false, true, false, false, true, true, false, true, true, false, false, true, false, true, false, true, true, false, true, true, false, true, false, true, true, false, true, false, false, false, true, true, false, false, true, false, false, true, false, true, false, false, true, true, true, false, true, true, false, false, false, false, true, true, false, true, false, true, true, false, false, true, true, false, true, false, false, false, true, true, true, false]
  , [true, false, false, true, false, true, true, false, false, true, false, false, true, true, false, true, true, false, false, true, true, false, true, false, true, false, true, false, true, true, false, true, false, true, true, false, true, false, false, true, false, false, false, false, true, true, false, true, false, false, true, true, true, true, false, true, false, false, false, false, true, true, false, true, false, false, true, false, true, true, true, false, true, false, false, false, true, true, true, false]
  , [true, false, false, true, false, true, true, false, false, true, false, true, true, false, false, false, true, true, false, true, false, true, false, true, true, false, true, false, false, true, true, false, true, false, true, true, false, true, true, false, false, false, true, false, false, true, false, false, true, false, true, true, true, false, false, true, true, false, false, true, true, false, false, true, false, true, true, false, false, true, true, false, true, false, false, false, true, true, true, false]
  , [true, false, false, true, false, true, true, false, false, true, true, false, false, true, false, true, false, true, false, true, false, true, false, false, true, true, false, true, false, true, false, true, true, false, true, false, false, true, false, true, true, false, true, false, false, true, false, true, false, false, true, true, true, false, true, true, false, false, false, false, true, true, false, true, false, true, true, true, false, false, false, false, true, true, true, false, true, true, false, false]
  , [true, false, false, true, true, false, true, true, false, false, false, false, true, false, true, true, false, false, true, true, false, true, false, true, true, false, true, true, false, true, false, true, true, false, true, false, false, false, true, true, false, false, true, false, false, true, false, true, false, true, false, true, true, false, true, true, false, false, false, false, true, false, true, true, false, true, true, false, false, true, true, true, false, false, false, false, true, true, false, true]
  , [true, false, false, true, true, false, true, true, false, false, false, false, true, false, true, true, false, false, true, true, true, false, true, false, true, false, true, false, true, true, false, true, false, true, false, true, true, false, true, false, false, false, true, false, true, false, true, false, false, true, true, false, true, true, false, false, true, false, false, false, true, false, true, true, false, false, true, false, true, true, true, true, false, false, false, true, false, false, true, true]
  , [true, false, false, true, true, false, true, true, false, false, false, false, true, false, true, true, false, false, true, true, true, false, true, false, true, false, true, false, true, true, false, true, false, true, true, false, true, false, false, true, false, false, false, false, true, true, false, true, false, true, false, true, false, true, true, false, false, true, true, false, false, true, true, false, false, true, false, true, true, false, false, true, true, false, true, false, true, false, false, true]
  , [true, false, false, true, true, false, true, true, false, false, false, false, true, false, true, true, false, false, true, true, true, false, true, false, true, false, true, false, true, true, false, true, false, true, true, false, true, false, false, true, false, false, false, false, true, true, false, true, false, true, false, true, true, true, false, true, false, false, false, false, true, false, true, true, false, false, true, false, true, true, true, true, false, false, false, false, true, true, false, true]
  , [true, false, false, true, true, false, true, true, false, false, false, true, false, false, false, true, false, true, true, true, true, false, true, false, true, false, true, false, true, false, true, true, false, false, true, true, false, true, false, true, false, false, false, false, true, true, false, true, true, false, false, true, false, true, false, true, true, false, false, true, true, false, true, true, false, false, true, false, true, false, true, true, false, false, false, false, true, true, false, true]
  , [true, false, false, true, true, false, true, true, false, false, true, false, true, false, true, false, false, true, false, true, false, false, true, false, false, true, true, false, true, true, false, true, false, true, true, false, true, true, false, false, true, false, false, false, true, true, false, true, false, true, false, true, true, true, false, true, false, false, false, false, true, false, true, true, false, false, true, true, false, true, true, false, false, true, true, false, false, true, false, true]
  , [true, false, true, false, false, false, true, false, true, true, false, false, true, true, false, true, true, false, false, true, false, true, false, true, true, false, true, true, false, false, true, true, false, false, true, false, false, false, true, true, false, true, false, true, false, true, false, true, true, false, false, true, false, false, true, true, false, true, true, false, true, true, false, true, false, true, false, false, false, true, true, false, true, false, false, false, true, true, true, false]
  , [true, false, true, false, false, false, true, false, true, true, true, false, false, true, false, true, false, true, false, false, true, true, true, false, true, false, false, true, true, false, false, true, false, true, false, false, true, false, false, true, true, true, false, false, true, true, false, true, true, false, false, true, false, true, true, false, false, true, true, false, true, true, false, false, false, true, false, true, true, false, false, false, true, true, true, false, true, true, false, false]
  , [true, false, true, false, false, false, true, false, true, true, true, false, false, true, false, true, false, true, false, true, false, true, false, false, true, true, false, true, false, false, true, true, false, false, false, true, false, true, true, false, true, true, true, true, false, false, true, false, true, false, true, false, false, false, true, false, true, true, true, false, true, true, false, true, false, true, false, true, false, false, false, false, true, true, true, true, false, false, true, false]
  , [true, false, true, false, false, false, true, false, true, true, true, false, false, true, false, true, false, true, false, true, false, true, false, false, true, true, false, true, false, false, true, true, false, false, true, false, false, true, false, true, true, true, false, true, false, true, false, true, true, false, false, true, false, false, true, true, false, true, true, false, true, true, false, true, false, true, false, true, false, false, false, false, true, true, true, false, true, true, false, false]
  , [true, false, true, false, false, false, true, false, true, true, true, false, false, true, false, true, false, true, false, true, false, true, false, false, true, true, false, true, false, false, true, true, false, false, true, false, false, true, false, true, true, true, false, true, false, true, false, true, true, false, false, true, false, true, false, true, true, false, false, true, true, false, true, true, true, false, false, false, true, false, false, true, false, true, false, true, true, true, false, false]
  , [true, false, true, false, false, false, true, false, true, true, true, false, true, false, true, false, false, true, false, true, false, true, false, false, true, true, false, false, false, true, true, false, false, true, true, false, true, true, false, false, true, true, false, true, false, true, false, false, true, true, false, true, true, false, false, true, false, true, true, false, true, false, false, true, false, true, false, true, false, true, false, false, true, true, true, false, true, true, false, false]
  , [true, false, true, true, false, false, false, true, true, false, false, false, true, false, true, true, false, false, true, true, true, false, true, false, true, false, true, false, false, true, true, false, false, true, true, false, true, false, false, true, false, true, false, true, true, false, false, false, true, true, false, true, true, false, false, true, false, true, true, false, true, false, false, true, false, false, true, false, true, true, true, true, false, false, false, false, true, true, false, true]
  , [true, false, true, true, false, false, false, true, true, false, true, false, false, true, false, true, false, true, false, true, false, false, true, false, false, true, true, true, false, false, true, true, false, false, true, false, false, true, false, true, true, true, false, true, true, false, false, true, true, false, false, true, false, false, true, true, false, true, true, false, true, true, false, true, false, false, true, true, false, false, true, false, false, true, true, false, false, true, false, true]
  , [true, false, true, true, false, false, false, true, true, false, true, false, true, false, true, false, false, true, false, false, false, true, true, true, false, false, true, true, false, true, false, false, true, true, false, false, true, false, true, false, true, true, true, false, true, false, false, false, true, true, false, true, true, false, true, false, false, true, true, false, true, false, false, false, false, true, true, true, false, true, true, false, false, true, true, false, false, true, false, true]
  , [true, false, true, true, false, false, false, true, true, false, true, false, true, false, true, false, false, true, false, true, false, false, true, false, false, true, true, false, false, true, true, false, false, true, true, false, true, true, false, false, true, true, false, true, true, false, false, false, true, true, false, true, false, true, false, false, true, true, true, true, false, false, true, false, true, false, false, true, true, false, false, true, false, true, true, true, false, false, false, true]
  , [true, false, true, true, false, false, false, true, true, false, true, false, true, false, true, false, false, true, false, true, false, false, true, false, false, true, true, false, false, true, true, false, false, true, true, false, true, true, false, false, true, true, false, true, true, false, false, false, true, true, false, true, true, false, false, true, false, true, true, false, true, false, false, true, false, false, true, true, false, true, true, false, false, true, true, false, false, true, false, true]
  , [true, false, true, true, false, false, false, true, true, false, true, false, true, false, true, false, false, true, false, true, false, false, true, false, false, true, true, false, false, true, true, false, false, true, true, true, false, true, true, false, false, false, true, true, false, false, true, false, true, false, true, true, true, false, false, true, true, false, true, false, true, false, false, true, false, false, true, true, false, true, true, false, false, true, false, true, false, true, true, false]
  , [true, true, false, false, true, false, true, false, true, false, false, false, true, false, true, true, false, false, true, true, true, false, false, false, true, true, false, false, true, true, false, true, false, true, true, false, true, false, false, true, false, false, false, true, false, true, true, true, false, true, false, true, true, true, false, true, false, false, false, false, true, false, true, true, true, false, false, false, true, true, false, true, false, true, false, true, true, true, false, false]
  , [true, true, false, false, true, false, true, false, true, false, false, true, false, false, false, true, false, true, true, false, true, true, false, true, true, false, false, true, true, false, false, true, true, false, false, true, false, false, true, true, false, false, true, false, false, true, true, true, true, false, false, true, false, true, true, false, true, false, false, true, true, false, true, false, true, true, false, false, true, false, false, true, false, true, false, true, true, true, false, false]
  , [true, true, false, false, true, false, true, false, true, false, false, true, false, false, false, true, false, true, true, true, true, false, false, false, true, true, false, false, true, false, true, true, false, false, false, true, true, true, false, false, true, true, false, true, true, false, true, false, true, true, false, false, false, true, false, false, true, true, false, true, true, false, true, true, true, false, false, false, true, false, false, true, false, true, true, true, false, false, false, true]
  , [true, true, false, false, true, false, true, false, true, false, false, true, false, false, false, true, false, true, true, true, true, false, false, false, true, true, false, false, true, false, true, true, false, false, true, true, false, true, false, true, false, false, false, true, false, true, true, true, true, false, false, true, false, false, true, true, false, true, true, false, true, true, false, true, false, true, false, true, false, false, false, false, true, true, true, false, true, true, false, false]
  , [true, true, false, false, true, false, true, false, true, false, false, true, false, false, false, true, false, true, true, true, true, false, false, false, true, true, false, false, true, false, true, true, false, false, true, true, false, true, false, true, false, false, false, true, false, true, true, true, true, false, false, true, false, true, false, true, true, false, false, true, true, false, true, true, true, false, false, false, true, false, false, true, false, true, false, true, true, true, false, false]
  , [true, true, false, false, true, false, true, false, true, false, false, true, true, false, false, false, true, true, false, true, false, false, false, true, false, true, true, false, true, false, true, true, false, false, true, true, false, true, true, false, false, false, false, true, false, true, true, true, true, false, false, true, false, true, false, true, true, false, false, true, true, false, true, true, true, false, false, false, false, true, true, false, false, true, false, true, false, true, true, false]
  , [true, true, false, true, false, true, false, false, true, false, false, false, true, true, false, true, true, false, false, true, false, false, false, true, false, true, true, true, false, true, false, true, true, false, true, false, false, false, true, true, false, false, true, true, false, false, true, true, false, false, true, true, true, false, true, true, false, false, false, false, true, true, false, true, true, false, true, false, false, true, true, false, false, true, false, true, false, true, true, false]
  , [true, true, false, true, false, true, false, false, true, false, false, true, false, false, false, true, false, true, true, true, true, false, false, false, true, true, false, false, false, true, true, false, true, false, true, true, false, true, false, true, false, false, true, true, false, false, true, false, true, false, true, true, true, false, false, true, true, false, false, true, true, false, false, true, true, false, true, false, true, false, false, true, false, true, false, true, true, true, false, false]
  , [true, true, false, true, false, true, false, false, true, false, false, true, true, false, false, false, true, true, false, false, true, false, true, true, false, false, true, false, true, true, false, false, true, true, false, true, true, false, true, false, false, false, true, false, true, false, true, false, true, false, true, true, true, true, false, false, true, false, false, true, true, false, false, false, true, false, true, false, true, true, true, false, false, true, false, true, false, true, true, false]
  , [true, true, false, true, false, true, false, false, true, false, false, true, true, false, false, false, true, true, false, true, false, false, false, true, false, true, true, false, false, true, true, false, true, false, true, false, true, true, false, false, true, true, false, true, true, false, false, false, true, true, false, true, true, false, false, true, false, true, false, true, true, false, false, true, true, false, true, false, false, true, true, false, false, true, true, false, false, true, false, true]
  , [true, true, false, true, false, true, false, false, true, false, false, true, true, false, false, false, true, true, false, true, false, false, false, true, false, true, true, false, false, true, true, false, true, false, true, true, false, true, true, false, false, false, true, true, false, false, true, false, true, false, true, true, false, false, true, false, true, true, true, true, false, true, false, false, true, true, false, true, false, false, false, false, true, true, true, true, false, false, true, false]
  , [true, true, false, true, false, true, false, false, true, false, false, true, true, false, false, false, true, true, false, true, false, false, false, true, false, true, true, false, false, true, true, false, true, false, true, true, false, true, true, false, false, false, true, true, false, false, true, false, true, false, true, true, true, false, false, true, true, false, false, true, true, false, false, true, true, false, true, false, false, true, true, false, false, true, false, true, false, true, true, false]
  ]

/-- `false` selects `k16Untwisted`; `true` selects `k16Twisted`. -/
def clebschCompletionTargets : List Bool :=
  [false, true, true, true, true, true, true, false, true, true, true, true, true, false, true, true, true, true, true, true, false, true, true, true, true, true, false, true, true, true, true, true, true, false, true, true, true, true, false, true, true, true, true, true, true, false, true, true, true, true, true, false, true, true, true, true, true, true, false, true, true, true, true, true, false, true, true, true, true, true, true, false]

/-- Direct vertex maps from each canonical completion to its critical template. -/
def clebschCompletionTemplateMaps : List (Fin 16 → Fin 16) := [
  ![0, 4, 6, 2, 1, 5, 7, 12, 9, 11, 15, 13, 8, 10, 14, 3]
  , ![0, 4, 9, 13, 10, 14, 3, 8, 6, 11, 15, 2, 12, 1, 5, 7]
  , ![0, 9, 4, 13, 15, 6, 11, 8, 14, 3, 10, 7, 1, 12, 5, 2]
  , ![0, 4, 6, 2, 1, 5, 7, 12, 9, 11, 15, 13, 8, 10, 14, 3]
  , ![0, 5, 6, 3, 1, 4, 7, 10, 14, 13, 8, 11, 15, 12, 9, 2]
  , ![0, 5, 14, 11, 12, 9, 2, 15, 6, 13, 8, 3, 10, 1, 4, 7]
  , ![0, 5, 6, 3, 8, 13, 14, 10, 7, 4, 1, 2, 15, 12, 9, 11]
  , ![0, 4, 6, 2, 15, 11, 9, 12, 7, 5, 1, 3, 8, 10, 14, 13]
  , ![0, 9, 4, 13, 10, 3, 14, 8, 11, 6, 15, 2, 1, 12, 5, 7]
  , ![0, 4, 9, 13, 15, 11, 6, 8, 3, 14, 10, 7, 12, 1, 5, 2]
  , ![0, 4, 6, 2, 15, 11, 9, 12, 7, 5, 1, 3, 8, 10, 14, 13]
  , ![0, 5, 14, 11, 8, 13, 6, 15, 2, 9, 12, 7, 10, 1, 4, 3]
  , ![0, 9, 7, 14, 12, 5, 11, 8, 13, 3, 10, 4, 1, 15, 6, 2]
  , ![0, 4, 2, 6, 1, 5, 3, 8, 13, 11, 15, 9, 12, 10, 14, 7]
  , ![0, 4, 13, 9, 10, 14, 7, 12, 2, 11, 15, 6, 8, 1, 5, 3]
  , ![0, 4, 2, 6, 1, 5, 3, 8, 13, 11, 15, 9, 12, 10, 14, 7]
  , ![0, 5, 3, 6, 1, 4, 2, 15, 11, 13, 8, 14, 10, 12, 9, 7]
  , ![0, 5, 11, 14, 12, 9, 7, 10, 3, 13, 8, 6, 15, 1, 4, 2]
  , ![0, 5, 3, 6, 8, 13, 11, 15, 2, 4, 1, 7, 10, 12, 9, 14]
  , ![0, 9, 7, 14, 10, 3, 13, 8, 11, 5, 12, 2, 1, 15, 6, 4]
  , ![0, 4, 2, 6, 15, 11, 13, 8, 3, 5, 1, 7, 12, 10, 14, 9]
  , ![0, 4, 13, 9, 15, 11, 2, 12, 7, 14, 10, 3, 8, 1, 5, 6]
  , ![0, 4, 2, 6, 15, 11, 13, 8, 3, 5, 1, 7, 12, 10, 14, 9]
  , ![0, 5, 11, 14, 8, 13, 3, 10, 7, 9, 12, 2, 15, 1, 4, 6]
  , ![0, 5, 2, 7, 12, 9, 14, 10, 3, 4, 1, 6, 15, 8, 13, 11]
  , ![0, 5, 7, 2, 1, 4, 6, 15, 11, 9, 12, 14, 10, 8, 13, 3]
  , ![0, 4, 3, 7, 10, 14, 9, 12, 2, 5, 1, 6, 8, 15, 11, 13]
  , ![0, 4, 3, 7, 10, 14, 9, 12, 2, 5, 1, 6, 8, 15, 11, 13]
  , ![0, 4, 7, 3, 1, 5, 6, 8, 13, 14, 10, 9, 12, 15, 11, 2]
  , ![0, 9, 2, 11, 12, 5, 14, 8, 13, 6, 15, 4, 1, 10, 3, 7]
  , ![0, 5, 2, 7, 1, 4, 3, 10, 14, 9, 12, 11, 15, 8, 13, 6]
  , ![0, 5, 7, 2, 12, 9, 11, 15, 6, 4, 1, 3, 10, 8, 13, 14]
  , ![0, 9, 2, 11, 15, 6, 13, 8, 14, 5, 12, 7, 1, 10, 3, 4]
  , ![0, 4, 3, 7, 1, 5, 2, 12, 9, 14, 10, 13, 8, 15, 11, 6]
  , ![0, 4, 7, 3, 10, 14, 13, 8, 6, 5, 1, 2, 12, 15, 11, 9]
  , ![0, 4, 3, 7, 1, 5, 2, 12, 9, 14, 10, 13, 8, 15, 11, 6]
  , ![0, 7, 9, 14, 12, 11, 5, 8, 3, 13, 10, 4, 15, 1, 6, 2]
  , ![0, 7, 14, 9, 10, 13, 4, 15, 2, 11, 12, 5, 8, 1, 6, 3]
  , ![0, 2, 4, 6, 1, 3, 5, 8, 11, 13, 15, 9, 10, 12, 14, 7]
  , ![0, 3, 5, 6, 1, 2, 4, 15, 13, 11, 8, 14, 12, 10, 9, 7]
  , ![0, 2, 4, 6, 1, 3, 5, 8, 11, 13, 15, 9, 10, 12, 14, 7]
  , ![0, 2, 6, 4, 15, 13, 9, 10, 7, 3, 1, 5, 8, 12, 14, 11]
  , ![0, 3, 5, 6, 8, 11, 13, 15, 4, 2, 1, 7, 12, 10, 9, 14]
  , ![0, 7, 14, 9, 12, 11, 2, 15, 4, 13, 10, 3, 8, 1, 6, 5]
  , ![0, 7, 9, 14, 10, 13, 3, 8, 5, 11, 12, 2, 15, 1, 6, 4]
  , ![0, 2, 4, 6, 15, 13, 11, 8, 5, 3, 1, 7, 10, 12, 14, 9]
  , ![0, 2, 4, 6, 15, 13, 11, 8, 5, 3, 1, 7, 10, 12, 14, 9]
  , ![0, 2, 6, 4, 1, 3, 7, 10, 9, 13, 15, 11, 8, 12, 14, 5]
  , ![0, 2, 5, 7, 12, 14, 9, 10, 4, 3, 1, 6, 8, 15, 13, 11]
  , ![0, 7, 5, 2, 1, 6, 4, 15, 9, 11, 12, 14, 8, 10, 13, 3]
  , ![0, 7, 4, 3, 1, 6, 5, 8, 14, 13, 10, 9, 15, 12, 11, 2]
  , ![0, 2, 5, 7, 12, 14, 9, 10, 4, 3, 1, 6, 8, 15, 13, 11]
  , ![0, 3, 4, 7, 10, 9, 14, 12, 5, 2, 1, 6, 15, 8, 11, 13]
  , ![0, 2, 9, 11, 12, 14, 5, 8, 6, 13, 15, 4, 10, 1, 3, 7]
  , ![0, 2, 5, 7, 1, 3, 4, 10, 9, 14, 12, 11, 8, 15, 13, 6]
  , ![0, 2, 9, 11, 15, 13, 6, 8, 5, 14, 12, 7, 10, 1, 3, 4]
  , ![0, 7, 5, 2, 12, 11, 9, 15, 4, 6, 1, 3, 8, 10, 13, 14]
  , ![0, 7, 4, 3, 10, 13, 14, 8, 5, 6, 1, 2, 15, 12, 11, 9]
  , ![0, 2, 5, 7, 1, 3, 4, 10, 9, 14, 12, 11, 8, 15, 13, 6]
  , ![0, 3, 4, 7, 1, 2, 5, 12, 14, 9, 10, 13, 15, 8, 11, 6]
  , ![0, 2, 7, 5, 12, 14, 11, 8, 6, 3, 1, 4, 10, 15, 13, 9]
  , ![0, 7, 2, 5, 1, 6, 3, 8, 14, 11, 12, 9, 15, 10, 13, 4]
  , ![0, 7, 3, 4, 1, 6, 2, 15, 9, 13, 10, 14, 8, 12, 11, 5]
  , ![0, 3, 7, 4, 10, 9, 13, 15, 6, 2, 1, 5, 12, 8, 11, 14]
  , ![0, 2, 7, 5, 12, 14, 11, 8, 6, 3, 1, 4, 10, 15, 13, 9]
  , ![0, 2, 11, 9, 12, 14, 7, 10, 4, 13, 15, 6, 8, 1, 3, 5]
  , ![0, 2, 7, 5, 1, 3, 6, 8, 11, 14, 12, 9, 10, 15, 13, 4]
  , ![0, 2, 11, 9, 15, 13, 4, 10, 7, 14, 12, 5, 8, 1, 3, 6]
  , ![0, 7, 2, 5, 12, 11, 14, 8, 3, 6, 1, 4, 15, 10, 13, 9]
  , ![0, 3, 7, 4, 1, 2, 6, 15, 13, 9, 10, 14, 12, 8, 11, 5]
  , ![0, 7, 3, 4, 10, 13, 9, 15, 2, 6, 1, 5, 8, 12, 11, 14]
  , ![0, 2, 7, 5, 1, 3, 6, 8, 11, 14, 12, 9, 10, 15, 13, 4]
  ]

/-- For each listed completion: representative number, vertex images,
and whether the two non-red colours are swapped. -/
def clebschCompletionOrbitMaps : List (Fin 2 × (Fin 16 → Fin 16) × Bool) := [
  (0, ![0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], false)
  , (1, ![0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], false)
  , (1, ![0, 2, 1, 3, 10, 8, 9, 7, 5, 6, 4, 15, 13, 12, 14, 11], false)
  , (1, ![0, 1, 8, 11, 13, 14, 15, 12, 2, 9, 10, 3, 7, 4, 5, 6], false)
  , (1, ![0, 8, 14, 6, 7, 5, 3, 4, 1, 15, 13, 11, 12, 10, 2, 9], false)
  , (1, ![0, 8, 1, 11, 10, 2, 9, 12, 14, 15, 13, 6, 4, 7, 5, 3], false)
  , (1, ![0, 8, 14, 6, 13, 15, 1, 4, 3, 5, 7, 9, 12, 10, 2, 11], false)
  , (0, ![0, 1, 2, 3, 10, 9, 8, 7, 6, 5, 4, 15, 12, 13, 14, 11], false)
  , (1, ![0, 2, 1, 3, 4, 6, 5, 7, 9, 8, 10, 11, 13, 12, 14, 15], false)
  , (1, ![0, 1, 2, 3, 10, 9, 8, 7, 6, 5, 4, 15, 12, 13, 14, 11], false)
  , (1, ![0, 1, 8, 11, 10, 9, 2, 12, 15, 14, 13, 6, 7, 4, 5, 3], false)
  , (1, ![0, 8, 1, 11, 13, 15, 14, 12, 9, 2, 10, 3, 4, 7, 5, 6], false)
  , (1, ![0, 2, 3, 1, 10, 8, 11, 13, 15, 6, 4, 5, 7, 12, 14, 9], false)
  , (0, ![0, 1, 3, 2, 4, 5, 15, 12, 11, 9, 10, 8, 7, 13, 14, 6], false)
  , (1, ![0, 1, 3, 2, 4, 5, 15, 12, 11, 9, 10, 8, 7, 13, 14, 6], false)
  , (1, ![0, 1, 11, 8, 13, 14, 6, 7, 3, 9, 10, 2, 12, 4, 5, 15], false)
  , (1, ![0, 8, 6, 14, 7, 5, 9, 12, 11, 15, 13, 1, 4, 10, 2, 3], false)
  , (1, ![0, 8, 11, 1, 10, 2, 3, 4, 6, 15, 13, 14, 12, 7, 5, 9], false)
  , (1, ![0, 8, 6, 14, 13, 15, 11, 12, 9, 5, 7, 3, 4, 10, 2, 1], false)
  , (1, ![0, 2, 3, 1, 4, 6, 15, 13, 11, 8, 10, 9, 7, 12, 14, 5], false)
  , (0, ![0, 1, 3, 2, 10, 9, 11, 12, 15, 5, 4, 6, 7, 13, 14, 8], false)
  , (1, ![0, 1, 3, 2, 10, 9, 11, 12, 15, 5, 4, 6, 7, 13, 14, 8], false)
  , (1, ![0, 1, 11, 8, 10, 9, 3, 7, 6, 14, 13, 15, 12, 4, 5, 2], false)
  , (1, ![0, 8, 11, 1, 13, 15, 6, 4, 3, 2, 10, 9, 12, 7, 5, 14], false)
  , (1, ![0, 8, 9, 3, 10, 2, 1, 4, 6, 5, 7, 14, 12, 13, 15, 11], false)
  , (1, ![0, 8, 3, 9, 7, 5, 14, 12, 11, 2, 10, 1, 4, 13, 15, 6], false)
  , (0, ![0, 1, 6, 15, 4, 5, 2, 12, 11, 14, 13, 8, 7, 10, 9, 3], false)
  , (1, ![0, 1, 6, 15, 4, 5, 2, 12, 11, 14, 13, 8, 7, 10, 9, 3], false)
  , (1, ![0, 1, 15, 6, 13, 14, 8, 7, 3, 5, 4, 2, 12, 10, 9, 11], false)
  , (1, ![0, 2, 9, 11, 10, 8, 1, 13, 15, 14, 12, 5, 7, 4, 6, 3], false)
  , (1, ![0, 8, 9, 3, 7, 5, 6, 4, 1, 2, 10, 11, 12, 13, 15, 14], false)
  , (1, ![0, 8, 3, 9, 10, 2, 11, 12, 14, 5, 7, 6, 4, 13, 15, 1], false)
  , (1, ![0, 2, 9, 11, 12, 14, 15, 13, 1, 8, 10, 3, 7, 4, 6, 5], false)
  , (0, ![0, 1, 6, 15, 13, 14, 11, 12, 2, 5, 4, 3, 7, 10, 9, 8], false)
  , (1, ![0, 1, 15, 6, 4, 5, 3, 7, 8, 14, 13, 11, 12, 10, 9, 2], false)
  , (1, ![0, 1, 6, 15, 13, 14, 11, 12, 2, 5, 4, 3, 7, 10, 9, 8], false)
  , (1, ![0, 1, 6, 15, 13, 14, 11, 12, 2, 5, 4, 3, 7, 10, 9, 8], true)
  , (1, ![0, 1, 15, 6, 4, 5, 3, 7, 8, 14, 13, 11, 12, 10, 9, 2], true)
  , (0, ![0, 1, 6, 15, 13, 14, 11, 12, 2, 5, 4, 3, 7, 10, 9, 8], true)
  , (1, ![0, 2, 9, 11, 12, 14, 15, 13, 1, 8, 10, 3, 7, 4, 6, 5], true)
  , (1, ![0, 8, 3, 9, 10, 2, 11, 12, 14, 5, 7, 6, 4, 13, 15, 1], true)
  , (1, ![0, 8, 9, 3, 7, 5, 6, 4, 1, 2, 10, 11, 12, 13, 15, 14], true)
  , (1, ![0, 2, 9, 11, 10, 8, 1, 13, 15, 14, 12, 5, 7, 4, 6, 3], true)
  , (1, ![0, 1, 15, 6, 13, 14, 8, 7, 3, 5, 4, 2, 12, 10, 9, 11], true)
  , (1, ![0, 1, 6, 15, 4, 5, 2, 12, 11, 14, 13, 8, 7, 10, 9, 3], true)
  , (0, ![0, 1, 6, 15, 4, 5, 2, 12, 11, 14, 13, 8, 7, 10, 9, 3], true)
  , (1, ![0, 8, 3, 9, 7, 5, 14, 12, 11, 2, 10, 1, 4, 13, 15, 6], true)
  , (1, ![0, 8, 9, 3, 10, 2, 1, 4, 6, 5, 7, 14, 12, 13, 15, 11], true)
  , (1, ![0, 8, 11, 1, 13, 15, 6, 4, 3, 2, 10, 9, 12, 7, 5, 14], true)
  , (1, ![0, 1, 11, 8, 10, 9, 3, 7, 6, 14, 13, 15, 12, 4, 5, 2], true)
  , (1, ![0, 1, 3, 2, 10, 9, 11, 12, 15, 5, 4, 6, 7, 13, 14, 8], true)
  , (0, ![0, 1, 3, 2, 10, 9, 11, 12, 15, 5, 4, 6, 7, 13, 14, 8], true)
  , (1, ![0, 2, 3, 1, 4, 6, 15, 13, 11, 8, 10, 9, 7, 12, 14, 5], true)
  , (1, ![0, 8, 6, 14, 13, 15, 11, 12, 9, 5, 7, 3, 4, 10, 2, 1], true)
  , (1, ![0, 8, 11, 1, 10, 2, 3, 4, 6, 15, 13, 14, 12, 7, 5, 9], true)
  , (1, ![0, 8, 6, 14, 7, 5, 9, 12, 11, 15, 13, 1, 4, 10, 2, 3], true)
  , (1, ![0, 1, 11, 8, 13, 14, 6, 7, 3, 9, 10, 2, 12, 4, 5, 15], true)
  , (1, ![0, 1, 3, 2, 4, 5, 15, 12, 11, 9, 10, 8, 7, 13, 14, 6], true)
  , (0, ![0, 1, 3, 2, 4, 5, 15, 12, 11, 9, 10, 8, 7, 13, 14, 6], true)
  , (1, ![0, 2, 3, 1, 10, 8, 11, 13, 15, 6, 4, 5, 7, 12, 14, 9], true)
  , (1, ![0, 8, 1, 11, 13, 15, 14, 12, 9, 2, 10, 3, 4, 7, 5, 6], true)
  , (1, ![0, 1, 8, 11, 10, 9, 2, 12, 15, 14, 13, 6, 7, 4, 5, 3], true)
  , (1, ![0, 1, 2, 3, 10, 9, 8, 7, 6, 5, 4, 15, 12, 13, 14, 11], true)
  , (1, ![0, 2, 1, 3, 4, 6, 5, 7, 9, 8, 10, 11, 13, 12, 14, 15], true)
  , (0, ![0, 1, 2, 3, 10, 9, 8, 7, 6, 5, 4, 15, 12, 13, 14, 11], true)
  , (1, ![0, 8, 14, 6, 13, 15, 1, 4, 3, 5, 7, 9, 12, 10, 2, 11], true)
  , (1, ![0, 8, 1, 11, 10, 2, 9, 12, 14, 15, 13, 6, 4, 7, 5, 3], true)
  , (1, ![0, 8, 14, 6, 7, 5, 3, 4, 1, 15, 13, 11, 12, 10, 2, 9], true)
  , (1, ![0, 1, 8, 11, 13, 14, 15, 12, 2, 9, 10, 3, 7, 4, 5, 6], true)
  , (1, ![0, 2, 1, 3, 10, 8, 9, 7, 5, 6, 4, 15, 13, 12, 14, 11], true)
  , (1, ![0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], true)
  , (0, ![0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], true)
  ]

end R4333
